/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testDuplicateWordsRepeatSame() {

        WordHelpers dupes = new WordHelpers();
        String toTest = "hello hello me hello hello";

        String deDupe = dupes.returnSingleWordFromWords(toTest);
        assertEquals("hello me hello", deDupe);

    }
    @Test
    public void testEnumTyping()
    {

        EnumHelper.ptypePrint(PrincipalType.valueOf("HUMAN"));
    }

    @Test
    public void testDoublingArray()
    {
        List<Integer> numbers = new ArrayList<Integer>(Arrays.asList(1,2,3));
        WordHelpers words = new WordHelpers();
        List<Integer> nums = words.doubling(numbers);

        Assert.assertEquals(new ArrayList<Integer>(nums),
                new ArrayList<Integer>(Arrays.asList(2,4,6)) );



    }

    @Test
    public void testCountStrEnd()
    {
        WordHelpers words = new WordHelpers();
        int count = words.countYZ("fez day");

        Assert.assertEquals(2,count);


    }
}
